// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file api/v1/auth.proto (package buygo.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetMeRequest, GetMeResponse, ListAssignableManagersRequest, ListAssignableManagersResponse, ListUsersRequest, ListUsersResponse, LoginRequest, LoginResponse, UpdateUserRoleRequest, UpdateUserRoleResponse } from "./auth_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service buygo.v1.AuthService
 */
export const AuthService = {
  typeName: "buygo.v1.AuthService",
  methods: {
    /**
     * Login with 3rd Party Token (Firebase)
     *
     * @generated from rpc buygo.v1.AuthService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Admin only: List users for management
     *
     * @generated from rpc buygo.v1.AuthService.ListUsers
     */
    listUsers: {
      name: "ListUsers",
      I: ListUsersRequest,
      O: ListUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Admin only: Update user role
     *
     * @generated from rpc buygo.v1.AuthService.UpdateUserRole
     */
    updateUserRole: {
      name: "UpdateUserRole",
      I: UpdateUserRoleRequest,
      O: UpdateUserRoleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Get current user profile (Self)
     *
     * @generated from rpc buygo.v1.AuthService.GetMe
     */
    getMe: {
      name: "GetMe",
      I: GetMeRequest,
      O: GetMeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * List Users eligible to be Managers (Creator or SysAdmin)
     *
     * @generated from rpc buygo.v1.AuthService.ListAssignableManagers
     */
    listAssignableManagers: {
      name: "ListAssignableManagers",
      I: ListAssignableManagersRequest,
      O: ListAssignableManagersResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

