// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file api/v1/event.proto (package buygo.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  CancelRegistrationRequest,
  CancelRegistrationResponse,
  CreateEventRequest,
  CreateEventResponse,
  GetEventRequest,
  GetEventResponse,
  GetMyRegistrationsRequest,
  GetMyRegistrationsResponse,
  ListEventRegistrationsRequest,
  ListEventRegistrationsResponse,
  ListEventsRequest,
  ListEventsResponse,
  ListManagerEventsRequest,
  ListManagerEventsResponse,
  RegisterEventRequest,
  RegisterEventResponse,
  UpdateEventRequest,
  UpdateEventResponse,
  UpdateEventStatusRequest,
  UpdateEventStatusResponse,
  UpdateRegistrationRequest,
  UpdateRegistrationResponse,
  UpdateRegistrationStatusRequest,
  UpdateRegistrationStatusResponse,
} from './event_pb.js';
import { MethodKind } from '@bufbuild/protobuf';

/**
 * @generated from service buygo.v1.EventService
 */
export const EventService = {
  typeName: 'buygo.v1.EventService',
  methods: {
    /**
     * @generated from rpc buygo.v1.EventService.CreateEvent
     */
    createEvent: {
      name: 'CreateEvent',
      I: CreateEventRequest,
      O: CreateEventResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.EventService.ListEvents
     */
    listEvents: {
      name: 'ListEvents',
      I: ListEventsRequest,
      O: ListEventsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.EventService.ListManagerEvents
     */
    listManagerEvents: {
      name: 'ListManagerEvents',
      I: ListManagerEventsRequest,
      O: ListManagerEventsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.EventService.GetEvent
     */
    getEvent: {
      name: 'GetEvent',
      I: GetEventRequest,
      O: GetEventResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Registration
     *
     * @generated from rpc buygo.v1.EventService.RegisterEvent
     */
    registerEvent: {
      name: 'RegisterEvent',
      I: RegisterEventRequest,
      O: RegisterEventResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.EventService.UpdateRegistration
     */
    updateRegistration: {
      name: 'UpdateRegistration',
      I: UpdateRegistrationRequest,
      O: UpdateRegistrationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.EventService.UpdateRegistrationStatus
     */
    updateRegistrationStatus: {
      name: 'UpdateRegistrationStatus',
      I: UpdateRegistrationStatusRequest,
      O: UpdateRegistrationStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.EventService.CancelRegistration
     */
    cancelRegistration: {
      name: 'CancelRegistration',
      I: CancelRegistrationRequest,
      O: CancelRegistrationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.EventService.GetMyRegistrations
     */
    getMyRegistrations: {
      name: 'GetMyRegistrations',
      I: GetMyRegistrationsRequest,
      O: GetMyRegistrationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.EventService.ListEventRegistrations
     */
    listEventRegistrations: {
      name: 'ListEventRegistrations',
      I: ListEventRegistrationsRequest,
      O: ListEventRegistrationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Management
     *
     * @generated from rpc buygo.v1.EventService.UpdateEvent
     */
    updateEvent: {
      name: 'UpdateEvent',
      I: UpdateEventRequest,
      O: UpdateEventResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.EventService.UpdateEventStatus
     */
    updateEventStatus: {
      name: 'UpdateEventStatus',
      I: UpdateEventStatusRequest,
      O: UpdateEventStatusResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
