// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file api/v1/event.proto (package buygo.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";
import { PaymentStatus } from "./groupbuy_pb.js";
import { User } from "./auth_pb.js";

/**
 * @generated from enum buygo.v1.EventStatus
 */
export enum EventStatus {
  /**
   * @generated from enum value: EVENT_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: EVENT_STATUS_DRAFT = 1;
   */
  DRAFT = 1,

  /**
   * @generated from enum value: EVENT_STATUS_ACTIVE = 2;
   */
  ACTIVE = 2,

  /**
   * @generated from enum value: EVENT_STATUS_ENDED = 3;
   */
  ENDED = 3,

  /**
   * @generated from enum value: EVENT_STATUS_ARCHIVED = 4;
   */
  ARCHIVED = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(EventStatus)
proto3.util.setEnumType(EventStatus, "buygo.v1.EventStatus", [
  { no: 0, name: "EVENT_STATUS_UNSPECIFIED" },
  { no: 1, name: "EVENT_STATUS_DRAFT" },
  { no: 2, name: "EVENT_STATUS_ACTIVE" },
  { no: 3, name: "EVENT_STATUS_ENDED" },
  { no: 4, name: "EVENT_STATUS_ARCHIVED" },
]);

/**
 * @generated from enum buygo.v1.RegistrationStatus
 */
export enum RegistrationStatus {
  /**
   * @generated from enum value: REGISTRATION_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: REGISTRATION_STATUS_PENDING = 1;
   */
  PENDING = 1,

  /**
   * @generated from enum value: REGISTRATION_STATUS_CONFIRMED = 2;
   */
  CONFIRMED = 2,

  /**
   * @generated from enum value: REGISTRATION_STATUS_CANCELLED = 3;
   */
  CANCELLED = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(RegistrationStatus)
proto3.util.setEnumType(RegistrationStatus, "buygo.v1.RegistrationStatus", [
  { no: 0, name: "REGISTRATION_STATUS_UNSPECIFIED" },
  { no: 1, name: "REGISTRATION_STATUS_PENDING" },
  { no: 2, name: "REGISTRATION_STATUS_CONFIRMED" },
  { no: 3, name: "REGISTRATION_STATUS_CANCELLED" },
]);

/**
 * ...
 *
 * @generated from message buygo.v1.UpdateRegistrationRequest
 */
export class UpdateRegistrationRequest extends Message<UpdateRegistrationRequest> {
  /**
   * @generated from field: string registration_id = 1;
   */
  registrationId = "";

  /**
   * @generated from field: repeated buygo.v1.RegisterItem items = 2;
   */
  items: RegisterItem[] = [];

  /**
   * @generated from field: string contact_info = 3;
   */
  contactInfo = "";

  /**
   * @generated from field: string notes = 4;
   */
  notes = "";

  constructor(data?: PartialMessage<UpdateRegistrationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.UpdateRegistrationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "registration_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "items", kind: "message", T: RegisterItem, repeated: true },
    { no: 3, name: "contact_info", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "notes", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateRegistrationRequest {
    return new UpdateRegistrationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateRegistrationRequest {
    return new UpdateRegistrationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateRegistrationRequest {
    return new UpdateRegistrationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateRegistrationRequest | PlainMessage<UpdateRegistrationRequest> | undefined, b: UpdateRegistrationRequest | PlainMessage<UpdateRegistrationRequest> | undefined): boolean {
    return proto3.util.equals(UpdateRegistrationRequest, a, b);
  }
}

/**
 * @generated from message buygo.v1.UpdateRegistrationResponse
 */
export class UpdateRegistrationResponse extends Message<UpdateRegistrationResponse> {
  /**
   * @generated from field: string registration_id = 1;
   */
  registrationId = "";

  /**
   * @generated from field: buygo.v1.RegistrationStatus status = 2;
   */
  status = RegistrationStatus.UNSPECIFIED;

  constructor(data?: PartialMessage<UpdateRegistrationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.UpdateRegistrationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "registration_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "status", kind: "enum", T: proto3.getEnumType(RegistrationStatus) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateRegistrationResponse {
    return new UpdateRegistrationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateRegistrationResponse {
    return new UpdateRegistrationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateRegistrationResponse {
    return new UpdateRegistrationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateRegistrationResponse | PlainMessage<UpdateRegistrationResponse> | undefined, b: UpdateRegistrationResponse | PlainMessage<UpdateRegistrationResponse> | undefined): boolean {
    return proto3.util.equals(UpdateRegistrationResponse, a, b);
  }
}

/**
 * @generated from message buygo.v1.UpdateRegistrationStatusRequest
 */
export class UpdateRegistrationStatusRequest extends Message<UpdateRegistrationStatusRequest> {
  /**
   * @generated from field: string registration_id = 1;
   */
  registrationId = "";

  /**
   * @generated from field: buygo.v1.RegistrationStatus status = 2;
   */
  status = RegistrationStatus.UNSPECIFIED;

  /**
   * @generated from field: buygo.v1.PaymentStatus payment_status = 3;
   */
  paymentStatus = PaymentStatus.UNSPECIFIED;

  constructor(data?: PartialMessage<UpdateRegistrationStatusRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.UpdateRegistrationStatusRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "registration_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "status", kind: "enum", T: proto3.getEnumType(RegistrationStatus) },
    { no: 3, name: "payment_status", kind: "enum", T: proto3.getEnumType(PaymentStatus) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateRegistrationStatusRequest {
    return new UpdateRegistrationStatusRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateRegistrationStatusRequest {
    return new UpdateRegistrationStatusRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateRegistrationStatusRequest {
    return new UpdateRegistrationStatusRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateRegistrationStatusRequest | PlainMessage<UpdateRegistrationStatusRequest> | undefined, b: UpdateRegistrationStatusRequest | PlainMessage<UpdateRegistrationStatusRequest> | undefined): boolean {
    return proto3.util.equals(UpdateRegistrationStatusRequest, a, b);
  }
}

/**
 * @generated from message buygo.v1.UpdateRegistrationStatusResponse
 */
export class UpdateRegistrationStatusResponse extends Message<UpdateRegistrationStatusResponse> {
  /**
   * @generated from field: string registration_id = 1;
   */
  registrationId = "";

  /**
   * @generated from field: buygo.v1.RegistrationStatus status = 2;
   */
  status = RegistrationStatus.UNSPECIFIED;

  /**
   * @generated from field: buygo.v1.PaymentStatus payment_status = 3;
   */
  paymentStatus = PaymentStatus.UNSPECIFIED;

  constructor(data?: PartialMessage<UpdateRegistrationStatusResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.UpdateRegistrationStatusResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "registration_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "status", kind: "enum", T: proto3.getEnumType(RegistrationStatus) },
    { no: 3, name: "payment_status", kind: "enum", T: proto3.getEnumType(PaymentStatus) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateRegistrationStatusResponse {
    return new UpdateRegistrationStatusResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateRegistrationStatusResponse {
    return new UpdateRegistrationStatusResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateRegistrationStatusResponse {
    return new UpdateRegistrationStatusResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateRegistrationStatusResponse | PlainMessage<UpdateRegistrationStatusResponse> | undefined, b: UpdateRegistrationStatusResponse | PlainMessage<UpdateRegistrationStatusResponse> | undefined): boolean {
    return proto3.util.equals(UpdateRegistrationStatusResponse, a, b);
  }
}

/**
 * @generated from message buygo.v1.Event
 */
export class Event extends Message<Event> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string title = 2;
   */
  title = "";

  /**
   * @generated from field: string description = 3;
   */
  description = "";

  /**
   * @generated from field: string cover_image_url = 4;
   */
  coverImageUrl = "";

  /**
   * @generated from field: buygo.v1.EventStatus status = 5;
   */
  status = EventStatus.UNSPECIFIED;

  /**
   * @generated from field: google.protobuf.Timestamp start_time = 6;
   */
  startTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp end_time = 7;
   */
  endTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp registration_deadline = 8;
   */
  registrationDeadline?: Timestamp;

  /**
   * @generated from field: string location = 9;
   */
  location = "";

  /**
   * @generated from field: buygo.v1.User creator = 10;
   */
  creator?: User;

  /**
   * @generated from field: repeated buygo.v1.User managers = 11;
   */
  managers: User[] = [];

  /**
   * @generated from field: repeated string payment_methods = 12;
   */
  paymentMethods: string[] = [];

  /**
   * @generated from field: repeated buygo.v1.EventItem items = 13;
   */
  items: EventItem[] = [];

  /**
   * @generated from field: bool allow_modification = 14;
   */
  allowModification = false;

  /**
   * @generated from field: repeated buygo.v1.DiscountRule discounts = 15;
   */
  discounts: DiscountRule[] = [];

  constructor(data?: PartialMessage<Event>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.Event";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "cover_image_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "status", kind: "enum", T: proto3.getEnumType(EventStatus) },
    { no: 6, name: "start_time", kind: "message", T: Timestamp },
    { no: 7, name: "end_time", kind: "message", T: Timestamp },
    { no: 8, name: "registration_deadline", kind: "message", T: Timestamp },
    { no: 9, name: "location", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "creator", kind: "message", T: User },
    { no: 11, name: "managers", kind: "message", T: User, repeated: true },
    { no: 12, name: "payment_methods", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 13, name: "items", kind: "message", T: EventItem, repeated: true },
    { no: 14, name: "allow_modification", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 15, name: "discounts", kind: "message", T: DiscountRule, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Event {
    return new Event().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Event {
    return new Event().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Event {
    return new Event().fromJsonString(jsonString, options);
  }

  static equals(a: Event | PlainMessage<Event> | undefined, b: Event | PlainMessage<Event> | undefined): boolean {
    return proto3.util.equals(Event, a, b);
  }
}

/**
 * @generated from message buygo.v1.EventItem
 */
export class EventItem extends Message<EventItem> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: int64 price = 3;
   */
  price = protoInt64.zero;

  /**
   * @generated from field: int32 min_participants = 4;
   */
  minParticipants = 0;

  /**
   * @generated from field: int32 max_participants = 5;
   */
  maxParticipants = 0;

  /**
   * @generated from field: google.protobuf.Timestamp start_time = 6;
   */
  startTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp end_time = 7;
   */
  endTime?: Timestamp;

  /**
   * @generated from field: bool allow_multiple = 8;
   */
  allowMultiple = false;

  constructor(data?: PartialMessage<EventItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.EventItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "price", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "min_participants", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "max_participants", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "start_time", kind: "message", T: Timestamp },
    { no: 7, name: "end_time", kind: "message", T: Timestamp },
    { no: 8, name: "allow_multiple", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventItem {
    return new EventItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventItem {
    return new EventItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventItem {
    return new EventItem().fromJsonString(jsonString, options);
  }

  static equals(a: EventItem | PlainMessage<EventItem> | undefined, b: EventItem | PlainMessage<EventItem> | undefined): boolean {
    return proto3.util.equals(EventItem, a, b);
  }
}

/**
 * @generated from message buygo.v1.DiscountRule
 */
export class DiscountRule extends Message<DiscountRule> {
  /**
   * Minimum items (sum of all items in registration)
   *
   * @generated from field: int32 min_quantity = 1;
   */
  minQuantity = 0;

  /**
   * Fixed amount off (e.g. 100 TWD)
   *
   * @generated from field: int64 discount_amount = 2;
   */
  discountAmount = protoInt64.zero;

  /**
   * Could add percentage later
   *
   * @generated from field: int32 min_distinct_items = 3;
   */
  minDistinctItems = 0;

  constructor(data?: PartialMessage<DiscountRule>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.DiscountRule";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "min_quantity", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "discount_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "min_distinct_items", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DiscountRule {
    return new DiscountRule().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DiscountRule {
    return new DiscountRule().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DiscountRule {
    return new DiscountRule().fromJsonString(jsonString, options);
  }

  static equals(a: DiscountRule | PlainMessage<DiscountRule> | undefined, b: DiscountRule | PlainMessage<DiscountRule> | undefined): boolean {
    return proto3.util.equals(DiscountRule, a, b);
  }
}

/**
 * @generated from message buygo.v1.GetEventRequest
 */
export class GetEventRequest extends Message<GetEventRequest> {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId = "";

  constructor(data?: PartialMessage<GetEventRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.GetEventRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEventRequest {
    return new GetEventRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEventRequest {
    return new GetEventRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEventRequest {
    return new GetEventRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetEventRequest | PlainMessage<GetEventRequest> | undefined, b: GetEventRequest | PlainMessage<GetEventRequest> | undefined): boolean {
    return proto3.util.equals(GetEventRequest, a, b);
  }
}

/**
 * @generated from message buygo.v1.GetEventResponse
 */
export class GetEventResponse extends Message<GetEventResponse> {
  /**
   * @generated from field: buygo.v1.Event event = 1;
   */
  event?: Event;

  constructor(data?: PartialMessage<GetEventResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.GetEventResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event", kind: "message", T: Event },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEventResponse {
    return new GetEventResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEventResponse {
    return new GetEventResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEventResponse {
    return new GetEventResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetEventResponse | PlainMessage<GetEventResponse> | undefined, b: GetEventResponse | PlainMessage<GetEventResponse> | undefined): boolean {
    return proto3.util.equals(GetEventResponse, a, b);
  }
}

/**
 * @generated from message buygo.v1.CreateEventRequest
 */
export class CreateEventRequest extends Message<CreateEventRequest> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: google.protobuf.Timestamp start_time = 3;
   */
  startTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp end_time = 4;
   */
  endTime?: Timestamp;

  /**
   * @generated from field: repeated buygo.v1.DiscountRule discounts = 5;
   */
  discounts: DiscountRule[] = [];

  /**
   * @generated from field: repeated buygo.v1.EventItem items = 6;
   */
  items: EventItem[] = [];

  constructor(data?: PartialMessage<CreateEventRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.CreateEventRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "start_time", kind: "message", T: Timestamp },
    { no: 4, name: "end_time", kind: "message", T: Timestamp },
    { no: 5, name: "discounts", kind: "message", T: DiscountRule, repeated: true },
    { no: 6, name: "items", kind: "message", T: EventItem, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateEventRequest {
    return new CreateEventRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateEventRequest {
    return new CreateEventRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateEventRequest {
    return new CreateEventRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateEventRequest | PlainMessage<CreateEventRequest> | undefined, b: CreateEventRequest | PlainMessage<CreateEventRequest> | undefined): boolean {
    return proto3.util.equals(CreateEventRequest, a, b);
  }
}

/**
 * @generated from message buygo.v1.CreateEventResponse
 */
export class CreateEventResponse extends Message<CreateEventResponse> {
  /**
   * @generated from field: buygo.v1.Event event = 1;
   */
  event?: Event;

  constructor(data?: PartialMessage<CreateEventResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.CreateEventResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event", kind: "message", T: Event },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateEventResponse {
    return new CreateEventResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateEventResponse {
    return new CreateEventResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateEventResponse {
    return new CreateEventResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateEventResponse | PlainMessage<CreateEventResponse> | undefined, b: CreateEventResponse | PlainMessage<CreateEventResponse> | undefined): boolean {
    return proto3.util.equals(CreateEventResponse, a, b);
  }
}

/**
 * @generated from message buygo.v1.UpdateEventRequest
 */
export class UpdateEventRequest extends Message<UpdateEventRequest> {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId = "";

  /**
   * @generated from field: string title = 2;
   */
  title = "";

  /**
   * @generated from field: string description = 3;
   */
  description = "";

  /**
   * @generated from field: google.protobuf.Timestamp start_time = 4;
   */
  startTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp end_time = 5;
   */
  endTime?: Timestamp;

  /**
   * @generated from field: string location = 6;
   */
  location = "";

  /**
   * @generated from field: string cover_image_url = 7;
   */
  coverImageUrl = "";

  /**
   * @generated from field: bool allow_modification = 8;
   */
  allowModification = false;

  /**
   * Full replace strategy for items
   *
   * @generated from field: repeated buygo.v1.EventItem items = 9;
   */
  items: EventItem[] = [];

  /**
   * @generated from field: repeated string manager_ids = 10;
   */
  managerIds: string[] = [];

  /**
   * @generated from field: repeated buygo.v1.DiscountRule discounts = 11;
   */
  discounts: DiscountRule[] = [];

  constructor(data?: PartialMessage<UpdateEventRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.UpdateEventRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "start_time", kind: "message", T: Timestamp },
    { no: 5, name: "end_time", kind: "message", T: Timestamp },
    { no: 6, name: "location", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "cover_image_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "allow_modification", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 9, name: "items", kind: "message", T: EventItem, repeated: true },
    { no: 10, name: "manager_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 11, name: "discounts", kind: "message", T: DiscountRule, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateEventRequest {
    return new UpdateEventRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateEventRequest {
    return new UpdateEventRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateEventRequest {
    return new UpdateEventRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateEventRequest | PlainMessage<UpdateEventRequest> | undefined, b: UpdateEventRequest | PlainMessage<UpdateEventRequest> | undefined): boolean {
    return proto3.util.equals(UpdateEventRequest, a, b);
  }
}

/**
 * @generated from message buygo.v1.UpdateEventResponse
 */
export class UpdateEventResponse extends Message<UpdateEventResponse> {
  /**
   * @generated from field: buygo.v1.Event event = 1;
   */
  event?: Event;

  constructor(data?: PartialMessage<UpdateEventResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.UpdateEventResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event", kind: "message", T: Event },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateEventResponse {
    return new UpdateEventResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateEventResponse {
    return new UpdateEventResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateEventResponse {
    return new UpdateEventResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateEventResponse | PlainMessage<UpdateEventResponse> | undefined, b: UpdateEventResponse | PlainMessage<UpdateEventResponse> | undefined): boolean {
    return proto3.util.equals(UpdateEventResponse, a, b);
  }
}

/**
 * @generated from message buygo.v1.UpdateEventStatusRequest
 */
export class UpdateEventStatusRequest extends Message<UpdateEventStatusRequest> {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId = "";

  /**
   * @generated from field: buygo.v1.EventStatus status = 2;
   */
  status = EventStatus.UNSPECIFIED;

  constructor(data?: PartialMessage<UpdateEventStatusRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.UpdateEventStatusRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "status", kind: "enum", T: proto3.getEnumType(EventStatus) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateEventStatusRequest {
    return new UpdateEventStatusRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateEventStatusRequest {
    return new UpdateEventStatusRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateEventStatusRequest {
    return new UpdateEventStatusRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateEventStatusRequest | PlainMessage<UpdateEventStatusRequest> | undefined, b: UpdateEventStatusRequest | PlainMessage<UpdateEventStatusRequest> | undefined): boolean {
    return proto3.util.equals(UpdateEventStatusRequest, a, b);
  }
}

/**
 * @generated from message buygo.v1.UpdateEventStatusResponse
 */
export class UpdateEventStatusResponse extends Message<UpdateEventStatusResponse> {
  /**
   * @generated from field: buygo.v1.Event event = 1;
   */
  event?: Event;

  constructor(data?: PartialMessage<UpdateEventStatusResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.UpdateEventStatusResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event", kind: "message", T: Event },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateEventStatusResponse {
    return new UpdateEventStatusResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateEventStatusResponse {
    return new UpdateEventStatusResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateEventStatusResponse {
    return new UpdateEventStatusResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateEventStatusResponse | PlainMessage<UpdateEventStatusResponse> | undefined, b: UpdateEventStatusResponse | PlainMessage<UpdateEventStatusResponse> | undefined): boolean {
    return proto3.util.equals(UpdateEventStatusResponse, a, b);
  }
}

/**
 * @generated from message buygo.v1.ListEventsRequest
 */
export class ListEventsRequest extends Message<ListEventsRequest> {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize = 0;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken = "";

  constructor(data?: PartialMessage<ListEventsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.ListEventsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListEventsRequest {
    return new ListEventsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListEventsRequest {
    return new ListEventsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListEventsRequest {
    return new ListEventsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListEventsRequest | PlainMessage<ListEventsRequest> | undefined, b: ListEventsRequest | PlainMessage<ListEventsRequest> | undefined): boolean {
    return proto3.util.equals(ListEventsRequest, a, b);
  }
}

/**
 * @generated from message buygo.v1.ListEventsResponse
 */
export class ListEventsResponse extends Message<ListEventsResponse> {
  /**
   * @generated from field: repeated buygo.v1.Event events = 1;
   */
  events: Event[] = [];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken = "";

  constructor(data?: PartialMessage<ListEventsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.ListEventsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "events", kind: "message", T: Event, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListEventsResponse {
    return new ListEventsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListEventsResponse {
    return new ListEventsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListEventsResponse {
    return new ListEventsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListEventsResponse | PlainMessage<ListEventsResponse> | undefined, b: ListEventsResponse | PlainMessage<ListEventsResponse> | undefined): boolean {
    return proto3.util.equals(ListEventsResponse, a, b);
  }
}

/**
 * @generated from message buygo.v1.ListManagerEventsRequest
 */
export class ListManagerEventsRequest extends Message<ListManagerEventsRequest> {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize = 0;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken = "";

  constructor(data?: PartialMessage<ListManagerEventsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.ListManagerEventsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListManagerEventsRequest {
    return new ListManagerEventsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListManagerEventsRequest {
    return new ListManagerEventsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListManagerEventsRequest {
    return new ListManagerEventsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListManagerEventsRequest | PlainMessage<ListManagerEventsRequest> | undefined, b: ListManagerEventsRequest | PlainMessage<ListManagerEventsRequest> | undefined): boolean {
    return proto3.util.equals(ListManagerEventsRequest, a, b);
  }
}

/**
 * @generated from message buygo.v1.ListManagerEventsResponse
 */
export class ListManagerEventsResponse extends Message<ListManagerEventsResponse> {
  /**
   * @generated from field: repeated buygo.v1.Event events = 1;
   */
  events: Event[] = [];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken = "";

  constructor(data?: PartialMessage<ListManagerEventsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.ListManagerEventsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "events", kind: "message", T: Event, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListManagerEventsResponse {
    return new ListManagerEventsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListManagerEventsResponse {
    return new ListManagerEventsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListManagerEventsResponse {
    return new ListManagerEventsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListManagerEventsResponse | PlainMessage<ListManagerEventsResponse> | undefined, b: ListManagerEventsResponse | PlainMessage<ListManagerEventsResponse> | undefined): boolean {
    return proto3.util.equals(ListManagerEventsResponse, a, b);
  }
}

/**
 * @generated from message buygo.v1.RegisterEventRequest
 */
export class RegisterEventRequest extends Message<RegisterEventRequest> {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId = "";

  /**
   * @generated from field: repeated buygo.v1.RegisterItem items = 2;
   */
  items: RegisterItem[] = [];

  /**
   * JSON or Struct
   *
   * @generated from field: string contact_info = 3;
   */
  contactInfo = "";

  /**
   * @generated from field: string notes = 4;
   */
  notes = "";

  constructor(data?: PartialMessage<RegisterEventRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.RegisterEventRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "items", kind: "message", T: RegisterItem, repeated: true },
    { no: 3, name: "contact_info", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "notes", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RegisterEventRequest {
    return new RegisterEventRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RegisterEventRequest {
    return new RegisterEventRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RegisterEventRequest {
    return new RegisterEventRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RegisterEventRequest | PlainMessage<RegisterEventRequest> | undefined, b: RegisterEventRequest | PlainMessage<RegisterEventRequest> | undefined): boolean {
    return proto3.util.equals(RegisterEventRequest, a, b);
  }
}

/**
 * @generated from message buygo.v1.RegisterItem
 */
export class RegisterItem extends Message<RegisterItem> {
  /**
   * @generated from field: string event_item_id = 1;
   */
  eventItemId = "";

  /**
   * Usually 1 for events, but maybe guest tickets
   *
   * @generated from field: int32 quantity = 2;
   */
  quantity = 0;

  constructor(data?: PartialMessage<RegisterItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.RegisterItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event_item_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "quantity", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RegisterItem {
    return new RegisterItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RegisterItem {
    return new RegisterItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RegisterItem {
    return new RegisterItem().fromJsonString(jsonString, options);
  }

  static equals(a: RegisterItem | PlainMessage<RegisterItem> | undefined, b: RegisterItem | PlainMessage<RegisterItem> | undefined): boolean {
    return proto3.util.equals(RegisterItem, a, b);
  }
}

/**
 * @generated from message buygo.v1.RegisterEventResponse
 */
export class RegisterEventResponse extends Message<RegisterEventResponse> {
  /**
   * @generated from field: string registration_id = 1;
   */
  registrationId = "";

  /**
   * @generated from field: buygo.v1.RegistrationStatus status = 2;
   */
  status = RegistrationStatus.UNSPECIFIED;

  constructor(data?: PartialMessage<RegisterEventResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.RegisterEventResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "registration_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "status", kind: "enum", T: proto3.getEnumType(RegistrationStatus) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RegisterEventResponse {
    return new RegisterEventResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RegisterEventResponse {
    return new RegisterEventResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RegisterEventResponse {
    return new RegisterEventResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RegisterEventResponse | PlainMessage<RegisterEventResponse> | undefined, b: RegisterEventResponse | PlainMessage<RegisterEventResponse> | undefined): boolean {
    return proto3.util.equals(RegisterEventResponse, a, b);
  }
}

/**
 * @generated from message buygo.v1.CancelRegistrationRequest
 */
export class CancelRegistrationRequest extends Message<CancelRegistrationRequest> {
  /**
   * @generated from field: string registration_id = 1;
   */
  registrationId = "";

  constructor(data?: PartialMessage<CancelRegistrationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.CancelRegistrationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "registration_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelRegistrationRequest {
    return new CancelRegistrationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelRegistrationRequest {
    return new CancelRegistrationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelRegistrationRequest {
    return new CancelRegistrationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CancelRegistrationRequest | PlainMessage<CancelRegistrationRequest> | undefined, b: CancelRegistrationRequest | PlainMessage<CancelRegistrationRequest> | undefined): boolean {
    return proto3.util.equals(CancelRegistrationRequest, a, b);
  }
}

/**
 * @generated from message buygo.v1.CancelRegistrationResponse
 */
export class CancelRegistrationResponse extends Message<CancelRegistrationResponse> {
  /**
   * @generated from field: string registration_id = 1;
   */
  registrationId = "";

  /**
   * @generated from field: buygo.v1.RegistrationStatus status = 2;
   */
  status = RegistrationStatus.UNSPECIFIED;

  constructor(data?: PartialMessage<CancelRegistrationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.CancelRegistrationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "registration_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "status", kind: "enum", T: proto3.getEnumType(RegistrationStatus) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelRegistrationResponse {
    return new CancelRegistrationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelRegistrationResponse {
    return new CancelRegistrationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelRegistrationResponse {
    return new CancelRegistrationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CancelRegistrationResponse | PlainMessage<CancelRegistrationResponse> | undefined, b: CancelRegistrationResponse | PlainMessage<CancelRegistrationResponse> | undefined): boolean {
    return proto3.util.equals(CancelRegistrationResponse, a, b);
  }
}

/**
 * @generated from message buygo.v1.Registration
 */
export class Registration extends Message<Registration> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string event_id = 2;
   */
  eventId = "";

  /**
   * @generated from field: string user_id = 3;
   */
  userId = "";

  /**
   * @generated from field: buygo.v1.RegistrationStatus status = 4;
   */
  status = RegistrationStatus.UNSPECIFIED;

  /**
   * @generated from field: buygo.v1.PaymentStatus payment_status = 5;
   */
  paymentStatus = PaymentStatus.UNSPECIFIED;

  /**
   * @generated from field: string contact_info = 6;
   */
  contactInfo = "";

  /**
   * @generated from field: string notes = 7;
   */
  notes = "";

  /**
   * @generated from field: repeated buygo.v1.RegisterItem selected_items = 8;
   */
  selectedItems: RegisterItem[] = [];

  /**
   * @generated from field: buygo.v1.User user = 9;
   */
  user?: User;

  /**
   * Snapshots at time of order
   *
   * @generated from field: int64 total_amount = 10;
   */
  totalAmount = protoInt64.zero;

  /**
   * @generated from field: int64 discount_applied = 11;
   */
  discountApplied = protoInt64.zero;

  constructor(data?: PartialMessage<Registration>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.Registration";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "status", kind: "enum", T: proto3.getEnumType(RegistrationStatus) },
    { no: 5, name: "payment_status", kind: "enum", T: proto3.getEnumType(PaymentStatus) },
    { no: 6, name: "contact_info", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "notes", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "selected_items", kind: "message", T: RegisterItem, repeated: true },
    { no: 9, name: "user", kind: "message", T: User },
    { no: 10, name: "total_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 11, name: "discount_applied", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Registration {
    return new Registration().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Registration {
    return new Registration().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Registration {
    return new Registration().fromJsonString(jsonString, options);
  }

  static equals(a: Registration | PlainMessage<Registration> | undefined, b: Registration | PlainMessage<Registration> | undefined): boolean {
    return proto3.util.equals(Registration, a, b);
  }
}

/**
 * @generated from message buygo.v1.GetMyRegistrationsRequest
 */
export class GetMyRegistrationsRequest extends Message<GetMyRegistrationsRequest> {
  constructor(data?: PartialMessage<GetMyRegistrationsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.GetMyRegistrationsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMyRegistrationsRequest {
    return new GetMyRegistrationsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMyRegistrationsRequest {
    return new GetMyRegistrationsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMyRegistrationsRequest {
    return new GetMyRegistrationsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetMyRegistrationsRequest | PlainMessage<GetMyRegistrationsRequest> | undefined, b: GetMyRegistrationsRequest | PlainMessage<GetMyRegistrationsRequest> | undefined): boolean {
    return proto3.util.equals(GetMyRegistrationsRequest, a, b);
  }
}

/**
 * @generated from message buygo.v1.GetMyRegistrationsResponse
 */
export class GetMyRegistrationsResponse extends Message<GetMyRegistrationsResponse> {
  /**
   * @generated from field: repeated buygo.v1.Registration registrations = 1;
   */
  registrations: Registration[] = [];

  constructor(data?: PartialMessage<GetMyRegistrationsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.GetMyRegistrationsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "registrations", kind: "message", T: Registration, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMyRegistrationsResponse {
    return new GetMyRegistrationsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMyRegistrationsResponse {
    return new GetMyRegistrationsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMyRegistrationsResponse {
    return new GetMyRegistrationsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetMyRegistrationsResponse | PlainMessage<GetMyRegistrationsResponse> | undefined, b: GetMyRegistrationsResponse | PlainMessage<GetMyRegistrationsResponse> | undefined): boolean {
    return proto3.util.equals(GetMyRegistrationsResponse, a, b);
  }
}

/**
 * @generated from message buygo.v1.ListEventRegistrationsRequest
 */
export class ListEventRegistrationsRequest extends Message<ListEventRegistrationsRequest> {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId = "";

  constructor(data?: PartialMessage<ListEventRegistrationsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.ListEventRegistrationsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListEventRegistrationsRequest {
    return new ListEventRegistrationsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListEventRegistrationsRequest {
    return new ListEventRegistrationsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListEventRegistrationsRequest {
    return new ListEventRegistrationsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListEventRegistrationsRequest | PlainMessage<ListEventRegistrationsRequest> | undefined, b: ListEventRegistrationsRequest | PlainMessage<ListEventRegistrationsRequest> | undefined): boolean {
    return proto3.util.equals(ListEventRegistrationsRequest, a, b);
  }
}

/**
 * @generated from message buygo.v1.ListEventRegistrationsResponse
 */
export class ListEventRegistrationsResponse extends Message<ListEventRegistrationsResponse> {
  /**
   * @generated from field: repeated buygo.v1.Registration registrations = 1;
   */
  registrations: Registration[] = [];

  constructor(data?: PartialMessage<ListEventRegistrationsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "buygo.v1.ListEventRegistrationsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "registrations", kind: "message", T: Registration, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListEventRegistrationsResponse {
    return new ListEventRegistrationsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListEventRegistrationsResponse {
    return new ListEventRegistrationsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListEventRegistrationsResponse {
    return new ListEventRegistrationsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListEventRegistrationsResponse | PlainMessage<ListEventRegistrationsResponse> | undefined, b: ListEventRegistrationsResponse | PlainMessage<ListEventRegistrationsResponse> | undefined): boolean {
    return proto3.util.equals(ListEventRegistrationsResponse, a, b);
  }
}

