// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file api/v1/groupbuy.proto (package buygo.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  AddProductRequest,
  AddProductResponse,
  BatchUpdateStatusRequest,
  BatchUpdateStatusResponse,
  CancelOrderRequest,
  CancelOrderResponse,
  ConfirmPaymentRequest,
  ConfirmPaymentResponse,
  CreateCategoryRequest,
  CreateCategoryResponse,
  CreateGroupBuyRequest,
  CreateGroupBuyResponse,
  CreateOrderRequest,
  CreateOrderResponse,
  CreatePriceTemplateRequest,
  CreatePriceTemplateResponse,
  DeletePriceTemplateRequest,
  DeletePriceTemplateResponse,
  GetGroupBuyRequest,
  GetGroupBuyResponse,
  GetMyGroupBuyOrderRequest,
  GetMyGroupBuyOrderResponse,
  GetMyOrdersRequest,
  GetMyOrdersResponse,
  GetPriceTemplateRequest,
  GetPriceTemplateResponse,
  ListCategoriesRequest,
  ListCategoriesResponse,
  ListGroupBuyOrdersRequest,
  ListGroupBuyOrdersResponse,
  ListGroupBuysRequest,
  ListGroupBuysResponse,
  ListManagerGroupBuysRequest,
  ListManagerGroupBuysResponse,
  ListPriceTemplatesRequest,
  ListPriceTemplatesResponse,
  UpdateGroupBuyRequest,
  UpdateGroupBuyResponse,
  UpdateOrderRequest,
  UpdateOrderResponse,
  UpdatePaymentInfoRequest,
  UpdatePaymentInfoResponse,
  UpdatePriceTemplateRequest,
  UpdatePriceTemplateResponse,
} from './groupbuy_pb.js';
import { MethodKind } from '@bufbuild/protobuf';

/**
 * @generated from service buygo.v1.GroupBuyService
 */
export const GroupBuyService = {
  typeName: 'buygo.v1.GroupBuyService',
  methods: {
    /**
     * GroupBuy Management (Creator/Admin)
     *
     * @generated from rpc buygo.v1.GroupBuyService.CreateGroupBuy
     */
    createGroupBuy: {
      name: 'CreateGroupBuy',
      I: CreateGroupBuyRequest,
      O: CreateGroupBuyResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.GroupBuyService.ListGroupBuys
     */
    listGroupBuys: {
      name: 'ListGroupBuys',
      I: ListGroupBuysRequest,
      O: ListGroupBuysResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.GroupBuyService.ListManagerGroupBuys
     */
    listManagerGroupBuys: {
      name: 'ListManagerGroupBuys',
      I: ListManagerGroupBuysRequest,
      O: ListManagerGroupBuysResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.GroupBuyService.GetGroupBuy
     */
    getGroupBuy: {
      name: 'GetGroupBuy',
      I: GetGroupBuyRequest,
      O: GetGroupBuyResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.GroupBuyService.UpdateGroupBuy
     */
    updateGroupBuy: {
      name: 'UpdateGroupBuy',
      I: UpdateGroupBuyRequest,
      O: UpdateGroupBuyResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Product Management (Creator/Admin)
     *
     * @generated from rpc buygo.v1.GroupBuyService.AddProduct
     */
    addProduct: {
      name: 'AddProduct',
      I: AddProductRequest,
      O: AddProductResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Category (Template) Methods
     *
     * @generated from rpc buygo.v1.GroupBuyService.CreateCategory
     */
    createCategory: {
      name: 'CreateCategory',
      I: CreateCategoryRequest,
      O: CreateCategoryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.GroupBuyService.ListCategories
     */
    listCategories: {
      name: 'ListCategories',
      I: ListCategoriesRequest,
      O: ListCategoriesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Order Management (User)
     *
     * @generated from rpc buygo.v1.GroupBuyService.CreateOrder
     */
    createOrder: {
      name: 'CreateOrder',
      I: CreateOrderRequest,
      O: CreateOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.GroupBuyService.CancelOrder
     */
    cancelOrder: {
      name: 'CancelOrder',
      I: CancelOrderRequest,
      O: CancelOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.GroupBuyService.GetMyGroupBuyOrder
     */
    getMyGroupBuyOrder: {
      name: 'GetMyGroupBuyOrder',
      I: GetMyGroupBuyOrderRequest,
      O: GetMyGroupBuyOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.GroupBuyService.UpdateOrder
     */
    updateOrder: {
      name: 'UpdateOrder',
      I: UpdateOrderRequest,
      O: UpdateOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.GroupBuyService.UpdatePaymentInfo
     */
    updatePaymentInfo: {
      name: 'UpdatePaymentInfo',
      I: UpdatePaymentInfoRequest,
      O: UpdatePaymentInfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.GroupBuyService.GetMyOrders
     */
    getMyOrders: {
      name: 'GetMyOrders',
      I: GetMyOrdersRequest,
      O: GetMyOrdersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Order Management (Manager)
     * Batch update status of items (FIFO)
     *
     * @generated from rpc buygo.v1.GroupBuyService.BatchUpdateStatus
     */
    batchUpdateStatus: {
      name: 'BatchUpdateStatus',
      I: BatchUpdateStatusRequest,
      O: BatchUpdateStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Confirm user payment
     * Confirm user payment
     *
     * @generated from rpc buygo.v1.GroupBuyService.ConfirmPayment
     */
    confirmPayment: {
      name: 'ConfirmPayment',
      I: ConfirmPaymentRequest,
      O: ConfirmPaymentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Manager: List Orders for a GroupBuy
     *
     * @generated from rpc buygo.v1.GroupBuyService.ListGroupBuyOrders
     */
    listGroupBuyOrders: {
      name: 'ListGroupBuyOrders',
      I: ListGroupBuyOrdersRequest,
      O: ListGroupBuyOrdersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Price Templates (Admin Only)
     *
     * @generated from rpc buygo.v1.GroupBuyService.CreatePriceTemplate
     */
    createPriceTemplate: {
      name: 'CreatePriceTemplate',
      I: CreatePriceTemplateRequest,
      O: CreatePriceTemplateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.GroupBuyService.ListPriceTemplates
     */
    listPriceTemplates: {
      name: 'ListPriceTemplates',
      I: ListPriceTemplatesRequest,
      O: ListPriceTemplatesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.GroupBuyService.GetPriceTemplate
     */
    getPriceTemplate: {
      name: 'GetPriceTemplate',
      I: GetPriceTemplateRequest,
      O: GetPriceTemplateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.GroupBuyService.UpdatePriceTemplate
     */
    updatePriceTemplate: {
      name: 'UpdatePriceTemplate',
      I: UpdatePriceTemplateRequest,
      O: UpdatePriceTemplateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.GroupBuyService.DeletePriceTemplate
     */
    deletePriceTemplate: {
      name: 'DeletePriceTemplate',
      I: DeletePriceTemplateRequest,
      O: DeletePriceTemplateResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
