// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file api/v1/project.proto (package buygo.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddProductRequest, AddProductResponse, BatchUpdateStatusRequest, BatchUpdateStatusResponse, CancelOrderRequest, CancelOrderResponse, ConfirmPaymentRequest, ConfirmPaymentResponse, CreateCategoryRequest, CreateCategoryResponse, CreateOrderRequest, CreateOrderResponse, CreatePriceTemplateRequest, CreatePriceTemplateResponse, CreateProjectRequest, CreateProjectResponse, DeletePriceTemplateRequest, DeletePriceTemplateResponse, GetMyOrdersRequest, GetMyOrdersResponse, GetMyProjectOrderRequest, GetMyProjectOrderResponse, GetPriceTemplateRequest, GetPriceTemplateResponse, GetProjectRequest, GetProjectResponse, ListCategoriesRequest, ListCategoriesResponse, ListManagerProjectsRequest, ListManagerProjectsResponse, ListPriceTemplatesRequest, ListPriceTemplatesResponse, ListProjectOrdersRequest, ListProjectOrdersResponse, ListProjectsRequest, ListProjectsResponse, UpdateOrderRequest, UpdateOrderResponse, UpdatePaymentInfoRequest, UpdatePaymentInfoResponse, UpdatePriceTemplateRequest, UpdatePriceTemplateResponse, UpdateProjectRequest, UpdateProjectResponse } from "./project_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service buygo.v1.ProjectService
 */
export const ProjectService = {
  typeName: "buygo.v1.ProjectService",
  methods: {
    /**
     * Project Management (Creator/Admin)
     *
     * @generated from rpc buygo.v1.ProjectService.CreateProject
     */
    createProject: {
      name: "CreateProject",
      I: CreateProjectRequest,
      O: CreateProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.ProjectService.ListProjects
     */
    listProjects: {
      name: "ListProjects",
      I: ListProjectsRequest,
      O: ListProjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.ProjectService.ListManagerProjects
     */
    listManagerProjects: {
      name: "ListManagerProjects",
      I: ListManagerProjectsRequest,
      O: ListManagerProjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.ProjectService.GetProject
     */
    getProject: {
      name: "GetProject",
      I: GetProjectRequest,
      O: GetProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.ProjectService.UpdateProject
     */
    updateProject: {
      name: "UpdateProject",
      I: UpdateProjectRequest,
      O: UpdateProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Product Management (Creator/Admin)
     *
     * @generated from rpc buygo.v1.ProjectService.AddProduct
     */
    addProduct: {
      name: "AddProduct",
      I: AddProductRequest,
      O: AddProductResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Category (Template) Methods
     *
     * @generated from rpc buygo.v1.ProjectService.CreateCategory
     */
    createCategory: {
      name: "CreateCategory",
      I: CreateCategoryRequest,
      O: CreateCategoryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.ProjectService.ListCategories
     */
    listCategories: {
      name: "ListCategories",
      I: ListCategoriesRequest,
      O: ListCategoriesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Order Management (User)
     *
     * @generated from rpc buygo.v1.ProjectService.CreateOrder
     */
    createOrder: {
      name: "CreateOrder",
      I: CreateOrderRequest,
      O: CreateOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.ProjectService.CancelOrder
     */
    cancelOrder: {
      name: "CancelOrder",
      I: CancelOrderRequest,
      O: CancelOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.ProjectService.GetMyProjectOrder
     */
    getMyProjectOrder: {
      name: "GetMyProjectOrder",
      I: GetMyProjectOrderRequest,
      O: GetMyProjectOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.ProjectService.UpdateOrder
     */
    updateOrder: {
      name: "UpdateOrder",
      I: UpdateOrderRequest,
      O: UpdateOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.ProjectService.UpdatePaymentInfo
     */
    updatePaymentInfo: {
      name: "UpdatePaymentInfo",
      I: UpdatePaymentInfoRequest,
      O: UpdatePaymentInfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.ProjectService.GetMyOrders
     */
    getMyOrders: {
      name: "GetMyOrders",
      I: GetMyOrdersRequest,
      O: GetMyOrdersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Order Management (Manager)
     * Batch update status of items (FIFO)
     *
     * @generated from rpc buygo.v1.ProjectService.BatchUpdateStatus
     */
    batchUpdateStatus: {
      name: "BatchUpdateStatus",
      I: BatchUpdateStatusRequest,
      O: BatchUpdateStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Confirm user payment
     * Confirm user payment
     *
     * @generated from rpc buygo.v1.ProjectService.ConfirmPayment
     */
    confirmPayment: {
      name: "ConfirmPayment",
      I: ConfirmPaymentRequest,
      O: ConfirmPaymentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Manager: List Orders for a Project
     *
     * @generated from rpc buygo.v1.ProjectService.ListProjectOrders
     */
    listProjectOrders: {
      name: "ListProjectOrders",
      I: ListProjectOrdersRequest,
      O: ListProjectOrdersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Price Templates (Admin Only)
     *
     * @generated from rpc buygo.v1.ProjectService.CreatePriceTemplate
     */
    createPriceTemplate: {
      name: "CreatePriceTemplate",
      I: CreatePriceTemplateRequest,
      O: CreatePriceTemplateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.ProjectService.ListPriceTemplates
     */
    listPriceTemplates: {
      name: "ListPriceTemplates",
      I: ListPriceTemplatesRequest,
      O: ListPriceTemplatesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.ProjectService.GetPriceTemplate
     */
    getPriceTemplate: {
      name: "GetPriceTemplate",
      I: GetPriceTemplateRequest,
      O: GetPriceTemplateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.ProjectService.UpdatePriceTemplate
     */
    updatePriceTemplate: {
      name: "UpdatePriceTemplate",
      I: UpdatePriceTemplateRequest,
      O: UpdatePriceTemplateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc buygo.v1.ProjectService.DeletePriceTemplate
     */
    deletePriceTemplate: {
      name: "DeletePriceTemplate",
      I: DeletePriceTemplateRequest,
      O: DeletePriceTemplateResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

